language: java
dist: trusty
matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk11
script: ./mvnw clean verify -Pci
cache:
  directories:
    - '$HOME/.m2/repository'
after_success:
  - bash <(curl -s https://codecov.io/bash)

