language: java
dist: trusty
matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk11
script: ./mvnw clean verify -Pci
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

