language: java
dist: trusty
matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk11
script: ./mvnw clean verify
after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

