language: java
dist: precise
matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk11
script: ./mvnw clean verify
after_success:
  - bash <(curl -s https://codecov.io/bash)
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

